import 'anime.dart';

const animeList = [
  Anime(
    title: 'КИНО',
    description: 'Одна из самых популярных советских рок-групп 1980-х годов, входившая в состав ленинградского рок-клуба.',
    genre: 'Russian Rock, Рок-музыка',
    year: 1981,
    rating: 10,
    imagePath: 'assets/images/anime1.jpg',
  ),
  Anime(
    title: 'Metallica',
    description: ' Американская метал-группа, созданная вокалистом и гитаристом Джеймсом Хетфилдом и барабанщиком Ларсом Ульрихом в Лос-Анджелесе, штат Калифорния, в 1981 году.',
    genre: 'трэш-метал, хеви-метал и хард-рок',
    year: 1981,
    rating: 10,
    imagePath: 'assets/images/anime2.jpg',
  ),
  Anime(
    title: 'The Beatles',
    description: 'Культовая британская рок-группа из Ливерпуля, основанная в 1960 году',
    genre: 'рок, поп и мерсибит',
    year: 1960,
    rating: 8.3,
    imagePath: 'assets/images/anime3.jpg',
  ),
  Anime(
    title: 'Linkin Park',
    description: 'Культовая американская рок-группа, основанная в 1996 году, ставшая одной из самых популярных и влиятельных команд 2000-х годов',
    genre: 'альтернативный рок, электроник-рок и поп-рок',
    year: 1996,
    rating: 9.9,
    imagePath: 'assets/images/anime4.jpg',
  ),
  Anime(
    title: 'AC/DC',
    description: 'Австралийская рок-группа, сформированная в Сиднее в ноябре 1973 года выходцами из Шотландии, братьями Малькольмом и Ангусом Янгами.',
    genre: 'хард-рок, блюз-рок и хэви-метал',
    year: 1973,
    rating: 10,
    imagePath: 'assets/images/anime5.jpg',
  ),
//   Anime(
//     title: 'My Hero Academia',
//     description: 'В мире супергероев подросток без способностей мечтает стать величайшим героем.',
//     genre: 'Экшен, Супергерои',
//     year: 2016,
//     rating: 8.4,
//     imagePath: 'assets/images/anime6.jpg',
//   ),
//   Anime(
//     title: 'Sword Art Online',
//     description: 'Игроки оказываются в ловушке виртуальной реальности, где смерть в игре означает смерть в реальности.',
//     genre: 'Фэнтези, Приключения',
//     year: 2012,
//     rating: 7.7,
//     imagePath: 'assets/images/anime7.jpg',
//   ),
//   Anime(
//     title: 'Fullmetal Alchemist: Brotherhood',
//     description: 'Два брата-алхимика ищут философский камень, чтобы вернуть утраченные тела.',
//     genre: 'Экшен, Фэнтези',
//     year: 2009,
//     rating: 9.1,
//     imagePath: 'assets/images/anime8.jpg',
//   ),
//   Anime(
//     title: 'Tokyo Ghoul',
//     description: 'Студент Канеки превращается в полу-гуля после трагического инцидента.',
//     genre: 'Ужасы, Экшен',
//     year: 2014,
//     rating: 7.9,
//     imagePath: 'assets/images/anime9.jpg',
//   ),
//   Anime(
//     title: 'Steins;Gate',
//     description: 'Учёный случайно изобретает машину времени и сталкивается с последствиями.',
//     genre: 'Sci-Fi, Триллер',
//     year: 2011,
//     rating: 9.1,
//     imagePath: 'assets/images/anime10.jpg',
//   ),
];